### ISSUE TITLE
[ENAN]: Bold Fonts for Selector and Timer

### ISSUE THREAD

**Issue by Gabbar-v7** [Gabbar-v7/KawaiiGRUB#2]
## Describe the enhancement

The font of the timer and selection menu is too small and weight is also less making it difficult to read. It can be improved by making the font bigger and bolder.

## Reason for the enhancement

- Difficult to read text
- Improved legibility

**Additional context :**
**Tried:**
- Font conversion to .pf2 and placing it in the theme folder to use it. Doesn't work.
- Tried calling with the name of font file.

---

- Font conversion command: `sudo grub-mkfont -s 24 -o font_name.pf2 font.otf`

**Comment by gaurav-null** [comment]
- the font has to be bold. (Fonts have diffrent specific style files. Download the bold one and use it here.)
- in the line 33 change the name

**Comment by Gabbar-v7** [comment]
The problem occurs when the secure boot is turned on especially with OS that allows it like Debian. The solution is to turn off secure boot in bios.
